import re
from pprint import pprint


def get_matches(source_strs):
    """Step 4. get every integer value for every file"""
    num_lists = []
    for source_str in source_strs:
        num_lists.append(list(set(re.findall("λ\d+\.*\d*λ", source_str))))
    return num_lists


if __name__ == "__main__":
    pprint(get_matches([
        '.new-game-accept-customization {\n'
        '    position: absolute;\n'
        '    z-index: 2;\n'
        '    width: λ90λpx; \n'
        '    height: λ40λpx; \n'
        '    left: λ1180λpx; \n'
        '    top: λ1180λpx; \n'
        '    font-size: λ18λpx;\n'
        '    color: #b6b6b6;\n'
        '    background-color: #6c6c6c;\n'
        '    border: λ1λpx solid #7e7e7e;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    border-radius: λ6λpx;\n'
        '    cursor: pointer;\n'
        '}\n'
        '.new-game-accept-customization:hover {\n'
        '    color: #606060;\n'
        '    background-color: #b6b6b6;\n'
        '} ',
        '.new-game-promo-list {\n'
        '    display: grid;\n'
        '    grid-template-columns: λ480λpx;\n'
        '    grid-template-rows: λ15λpx λ24λpx λ24λpx λ24λpx λ24λpx λ24λpx λ15λpx;\n'
        '    border: λ1λpx solid #707070\n'
        '\n'
        '}\n'
        '\n'
        '.promo-list-item {\n'
        '    color: #a9a9a9;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    font-size: λ15λpx;\n'
        '    text-align: left;\n'
        '    padding-top: λ4λpx;\n'
        '    overflow: hidden;\n'
        '    text-overflow: ellipsis;\n'
        '}\n'
        '\n'
        '.p-list-item1 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 2;\n'
        '    background-color: #5D5D5D;\n'
        '}\n'
        '\n'
        '.p-list-item2 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 3;\n'
        '    background-color: #515151;\n'
        '}\n'
        '\n'
        '.p-list-item3 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 4;\n'
        '    background-color: #5D5D5D;\n'
        '}\n'
        '\n'
        '.p-list-item4 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 5;\n'
        '    background-color: #515151;\n'
        '}\n'
        '\n'
        '.p-list-item5 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 6;\n'
        '    background-color: #5D5D5D;\n'
        '} ',
        '\n'
        '.promo-list-up-arrow {\n'
        '    grid-column: 1;\n'
        '    grid-row: 1;\n'
        '    cursor: pointer;\n'
        '}\n'
        '\n'
        '.promo-list-down-arrow {\n'
        '    grid-column: 1;\n'
        '    grid-row: 7;\n'
        '    cursor: pointer;\n'
        '}\n'
        '\n'
        '.promo-list-scroll-arrow {\n'
        '    position: absolute;\n'
        '    margin-top: λ3λpx;\n'
        '    width: λ7λpx;\n'
        '    height: λ6λpx;\n'
        '}',
        '.new-game-subs-header {\n'
        '    grid-column: 1 / 3;\n'
        '    grid-row: 1;\n'
        '    text-align: center;\n'
        '    color: #a9a9a9;\n'
        '    font-size: λ25λpx;\n'
        '    padding-left: λ85λpx;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    border: λ1λpx solid #707070;\n'
        '}\n'
        '\n'
        ' .new-game-bishop-label {\n'
        '    grid-column: 1;\n'
        '    grid-row: 3;\n'
        '    text-align: left;\n'
        '    font-size: λ20λpx;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    color: #a9a9a9;\n'
        '    padding-left: λ10λpx;\n'
        '    padding-top: λ5λpx;\n'
        '    background-color: #4e4e4e;\n'
        '    border-right: λ1λpx solid #707070;\n'
        '    /* border: λ1λpx solid #707070; */\n'
        '}\n'
        '.new-game-bishop-value {\n'
        '    grid-column: 2;\n'
        '    color: #a9a9a9;\n'
        '    background-color: #515151;\n'
        '    text-align: center;\n'
        '    font-size: λ20λpx;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    grid-row: 3;\n'
        '    padding-left: λ10λpx;\n'
        '    /* border: λ1λpx solid #707070; */\n'
        '}\n'
        '\n'
        '.new-game-knight-label {\n'
        '    grid-column: 1;\n'
        '    grid-row: 4;\n'
        '    text-align: left;\n'
        '    font-size: λ20λpx;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    color: #a9a9a9;\n'
        '    background-color: #4e4e4e;\n'
        '    border-right: λ1λpx solid #707070;\n'
        '    padding-left: λ10λpx;\n'
        '    padding-top: λ5λpx;\n'
        '    /* border: λ1λpx solid #707070; */\n'
        '}\n'
        '.new-game-knight-value {\n'
        '    grid-column: 2;\n'
        '    color: #a9a9a9;\n'
        '    background-color: #5D5D5D;\n'
        '    text-align: center;\n'
        '    font-size: λ20λpx;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    grid-row: 4;\n'
        '    padding-left: λ10λpx;\n'
        '    /* border: λ1λpx solid #707070; */\n'
        '}\n'
        '\n'
        '.new-game-rook-label {\n'
        '    grid-column: 1;\n'
        '    grid-row: 2;\n'
        '    text-align: left;\n'
        '    font-size: λ20λpx;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    color: #a9a9a9;\n'
        '    background-color: #4e4e4e;\n'
        '    border-right: λ1λpx solid #707070;\n'
        '    padding-left: λ10λpx;\n'
        '    padding-top: λ5λpx;\n'
        '    /* border: λ1λpx solid #707070; */\n'
        '}\n'
        '.new-game-rook-value {\n'
        '    grid-column: 2;\n'
        '    color: #a9a9a9;\n'
        '    background-color: #5D5D5D;\n'
        '    text-align: center;\n'
        '    font-size: λ20λpx;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    grid-row: 2;\n'
        '    padding-left: λ10λpx;\n'
        '    /* border: λ1λpx solid #707070; */\n'
        '\n'
        '}\n'
        '\n'
        '.new-game-queen-label {\n'
        '    grid-column: 1;\n'
        '    grid-row: 5;\n'
        '    text-align: left;\n'
        '    font-size: λ20λpx;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    color: #a9a9a9;\n'
        '    background-color: #4e4e4e;\n'
        '    border-right: λ1λpx solid #707070;\n'
        '    padding-left: λ10λpx;\n'
        '    padding-top: λ5λpx;\n'
        '    border-bottom: λ1λpx solid #707070;\n'
        '}\n'
        '.new-game-queen-value {\n'
        '    grid-column: 2;\n'
        '    color: #a9a9a9;\n'
        '    background-color: #515151;\n'
        '    text-align: center;\n'
        '    font-size: λ20λpx;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    padding-left: λ10λpx;\n'
        '    grid-row: 5;\n'
        '    border-bottom: λ1λpx solid #707070;\n'
        '}\n'
        '\n',
        '\n'
        '\n'
        '.new-game-display-board {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    grid-column: 1 \\ 3;\n'
        '    grid-row: 2;\n'
        '}',
        '.new-game-display-piece {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    width: λ20λpx;\n'
        '    height: λ20λpx;\n'
        '}',
        '.new-game-display-board-sqr1 {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    width: λ40λpx;\n'
        '    height: λ40λpx;\n'
        '    background-color: #707070;\n'
        '}\n'
        '\n'
        '.new-game-display-board-sqr2 {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    width: λ40λpx;\n'
        '    height: λ40λpx;\n'
        '    background-color: white;\n'
        '}\n'
        '\n'
        '.new-game-display-board-span-sqr {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    width: λ40λpx;\n'
        '    height: λ40λpx;\n'
        '    background-color: #EC2525;\n'
        '}\n'
        '\n'
        '.new-game-display-board-offset-sqr {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    width: λ40λpx;\n'
        '    height: λ40λpx;\n'
        '    background-color: #8b0000;\n'
        '}',
        '.new-game-expand-modal {\n'
        '    position: fixed;\n'
        '    z-index: 1;\n'
        '    top: 0;\n'
        '    left: 0;\n'
        '    width:λ100λ%;\n'
        '    height: λ100λ%;\n'
        '    background: rgba(0, 0, 0, 0.5);\n'
        '  }\n'
        '\n'
        '  .new-game-expand-modal-window {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    display: grid;\n'
        '    left: λ300λpx; \n'
        '    top: λ300λpx; \n'
        '    width: λ299λpx;\n'
        '    grid-template-columns: λ300λpx λ20λpx; \n'
        '    grid-template-rows: λ20λpx λ320λpx;\n'
        '    background-color: #515151;\n'
        '    color: white;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    font-size: λ12λpx; \n'
        '    overflow: wrap;\n'
        '}\n'
        '\n'
        '.new-game-expand-modal-window-title {\n'
        '  z-index: inherit;\n'
        '  grid-row: 1;\n'
        '  grid-column: 1;\n'
        '  color: white;\n'
        '  background-color: #515151;\n'
        '  border: λ1λpx solid #707070;\n'
        "  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '  font-size: λ15λpx;\n'
        '  overflow: hidden;\n'
        '  text-overflow: ellipsis;\n'
        '}\n'
        '\n'
        '.new-game-tooltip {\n'
        '  display: block;\n'
        '  position: absolute;\n'
        '  z-index: 3;\n'
        '  width: λ400λpx;\n'
        '  left: λ600λpx;\n'
        '  top: λ300λpx;\n'
        '  padding: λ5λpx 0;\n'
        '  color: #fff;\n'
        '  background-color: #515151;\n'
        '  font-size: λ15λpx;\n'
        "  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '  border-radius: λ6λpx;\n'
        '  word-wrap: break-word;\n'
        '}\n'
        '\n'
        '  /* .title:hover .tooltip {\n'
        '    visibility: visible;\n'
        '    z-index: 10;\n'
        '  } */\n'
        '\n'
        '.new-game-modal-window-unexpand {\n'
        '  z-index: inherit;\n'
        '  grid-row: 1;\n'
        '  grid-column: 2;\n'
        '  max-height: λ18λpx; \n'
        '  max-width: λ18λpx;\n'
        '  background-color: #515151;\n'
        '  border: λ1λpx solid #707070;\n'
        '  cursor: pointer;\n'
        '} \n'
        '\n'
        '\n',
        '.new-game-spans-header {\n'
        '    grid-row: 1;\n'
        '    grid-column: 2;\n'
        '    display: grid;\n'
        '    grid-template-rows: λ30λpx;\n'
        '    grid-template-columns: λ370λpx λ30λpx;\n'
        '    column-gap: λ20λpx;\n'
        '    border: λ1λpx solid #707070;\n'
        '}\n'
        '\n'
        '.new-game-offsets-header {\n'
        '    grid-row: 1;\n'
        '    grid-column: 3;\n'
        '    display: grid;\n'
        '    grid-template-rows: λ30λpx;\n'
        '    grid-template-columns: λ370λpx λ30λpx;\n'
        '    column-gap: λ20λpx;\n'
        '    border: λ1λpx solid #707070;\n'
        '}\n'
        '\n'
        '    .new-game-piece-wb-piece-name {\n'
        '        grid-row: 1;\n'
        '        grid-column: 1;\n'
        "        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '        font-size: λ15λpx;\n'
        '        padding-top: λ6λpx;\n'
        '        padding-left: λ50λpx;\n'
        '        color: #a9a9a9;\n'
        '        text-align: center;\n'
        '        overflow: hidden;\n'
        '        text-overflow: ellipsis;\n'
        '    }\n'
        '\n'
        '    .new-game-piece-expand-modal {\n'
        '        grid-row: 1;\n'
        '        grid-column: 2;\n'
        '        cursor: pointer;\n'
        '    }',
        '.new-game-spans-table {\n'
        '    grid-column: 2;\n'
        '    grid-row: 2;\n'
        '    display: grid;\n'
        '    grid-template-columns: λ420λpx;\n'
        '    grid-template-rows: λ15λpx λ24λpx λ24λpx λ24λpx λ24λpx λ24λpx λ15λpx;\n'
        '    border: λ1λpx solid #707070\n'
        '}\n'
        '\n'
        '.new-game-offsets-table {\n'
        '    grid-column: 3;\n'
        '    grid-row: 2;\n'
        '    display: grid;\n'
        '    grid-template-columns: λ420λpx;\n'
        '    grid-template-rows: λ15λpx λ24λpx λ24λpx λ24λpx λ24λpx λ24λpx λ15λpx;\n'
        '    border: λ1λpx solid #707070;\n'
        '}\n'
        '\n'
        '.range-list-item {\n'
        '    color: #a9a9a9;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    font-size: λ12λpx;\n'
        '    text-align: left;\n'
        '}\n'
        '\n'
        '.list-item1 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 2;\n'
        '    background-color: #5D5D5D;\n'
        '}\n'
        '\n'
        '.list-item2 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 3;\n'
        '    background-color: #515151;\n'
        '}\n'
        '\n'
        '.list-item3 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 4;\n'
        '    background-color: #5D5D5D;\n'
        '}\n'
        '\n'
        '.list-item4 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 5;\n'
        '    background-color: #515151;\n'
        '}\n'
        '\n'
        '.list-item5 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 6;\n'
        '    background-color: #5D5D5D;\n'
        '}',
        '\n'
        '.new-game-spans-up-arrow {\n'
        '    grid-column: 1;\n'
        '    grid-row: 1;\n'
        '    cursor: pointer;\n'
        '}\n'
        '\n'
        '.new-game-spans-down-arrow {\n'
        '    grid-column: 1;\n'
        '    grid-row: 7;\n'
        '    cursor: pointer;\n'
        '}\n'
        '\n'
        ' .new-game-offsets-up-arrow {\n'
        '    grid-column: 1;\n'
        '    grid-row: 1;\n'
        '    cursor: pointer;\n'
        '}\n'
        '\n'
        ' .new-game-offsets-down-arrow {\n'
        '    grid-column: 1;\n'
        '    grid-row: 7;\n'
        '    cursor: pointer;\n'
        '}\n'
        '\n'
        '.scroll-arrow {\n'
        '    position: relative;\n'
        '    top: -λ4λpx;\n'
        '    left: λ207λpx;\n'
        '    width: λ6λpx;\n'
        '    height: λ5λpx;\n'
        '}',
        '\n'
        '\n'
        '.new-game-w-or-b-profile {\n'
        '    z-index: inherit;\n'
        '    display: grid;\n'
        '    height: λ180λpx;\n'
        '    grid-template-columns: λ150λpx λ420λpx λ420λpx;\n'
        '    grid-template-rows: λ30λpx λ150λpx;\n'
        '    margin-top: λ20λpx;\n'
        '    background-color: #515151;\n'
        '    overflow: hidden;\n'
        '    text-overflow: ellipsis;\n'
        '}\n'
        '    \n'
        '    .new-game-w-or-b-profile-img-label {\n'
        '        grid-column:1;\n'
        '        grid-row: 1;\n'
        '        font-size: λ15λpx;\n'
        "        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '        text-align: center;\n'
        '        padding-top: λ6λpx;\n'
        '        color: #a9a9a9;\n'
        '        border: λ1λpx solid #707070;\n'
        '    }\n'
        '\n'
        '    .new-game-w-or-b-profile-img-window {\n'
        '        z-index: inherit;\n'
        '        grid-column: 1;\n'
        '        grid-row: 2;\n'
        '        object-fit: cover;\n'
        '        border: λ1λpx solid #707070;\n'
        '    }\n'
        '\n'
        '        .new-game-w-or-b-profile-img-window img {\n'
        '            z-index: inherit;\n'
        '            width: λ150λpx; \n'
        '            height: λ150λpx;\n'
        '            border-radius: λ5λpx;\n'
        '        }\n'
        '\n'
        '    .new-game-w-or-b-profile-spans-label {\n'
        '        grid-column: 2;\n'
        '        grid-row: 1;\n'
        '        \n'
        '    }\n'
        '\n'
        '    .new-game-w-or-b-profile-offsets-label {\n'
        '        grid-column: 3;\n'
        '        grid-row: 1;\n'
        '        \n'
        '    }\n',
        '.new-game-promotion-checkbox {\n'
        '    width: λ18λpx; \n'
        '    height: λ18λpx; \n'
        '    margin-top: λ5λpx; \n'
        '    background-color: #515151;\n'
        '    border: λ2λpx solid #707070;\n'
        '    border-radius: λ5λpx;\n'
        '    cursor: pointer;\n'
        '} .new-game-promotion-checkbox-selected {\n'
        '    width: λ18λpx; \n'
        '    height: λ18λpx; \n'
        '    margin-top: λ5λpx; \n'
        '    background-color: #515151;\n'
        '    border: λ2λpx solid #969696;\n'
        '    border-radius: λ5λpx;\n'
        '    cursor: pointer;\n'
        '}\n'
        '.new-game-promotion-checkbox-checkmark {\n'
        '    position: absolute;\n'
        '    max-height: λ18λpx; \n'
        '    max-width: λ18λpx; \n'
        '    padding: λ1λpx;\n'
        '    object-fit: contain;\n'
        '}\n',
        '.new-game-name-tooltip {\n'
        '    position: absolute;\n'
        '    display: block;\n'
        '    left: λ50λ%;\n'
        '    top: λ50λ%;\n'
        '    z-index: 3;\n'
        '    word-wrap: break-word;\n'
        '    color: white;\n'
        '\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    border-radius: λ5λpx;\n'
        '}',
        '.new-game-name-of-piece {\n'
        '    z-index: inherit;\n'
        '    grid-row: 1;\n'
        '    grid-column: 1 / 3;\n'
        '    padding-top: λ3λpx;\n'
        '    padding-left: λ9λpx; \n'
        '    padding-bottom: λ3λpx; \n'
        '    border-radius: λ3λpx; \n'
        '    color: #a9a9a9;\n'
        '    font-size: λ21λpx; \n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    overflow: hidden;\n'
        '    text-overflow: ellipsis;\n'
        '}\n',
        '\n'
        '.new-game-profile {\n'
        '    z-index: inherit;\n'
        '    height: λ480λpx;\n'
        '    border-bottom: λ1λpx solid #707070;\n'
        '}\n'
        '\n'
        '    /*container for w-or-b-profile*/\n'
        '    .new-game-profile-item {\n'
        '        z-index: inherit;\n'
        '        height: λ180λpx;\n'
        '        background-color: #515151;\n'
        '        margin-bottom: λ20λpx;\n'
        '    }\n'
        '\n'
        '    .new-game-profile-header {\n'
        '        display: grid;\n'
        '        z-index: inherit;\n'
        '        width: λ900λpx;\n'
        '        grid-template-rows: λ30λpx;\n'
        '        grid-template-columns: λ200λpx λ100λpx λ268λpx λ260λpx;\n'
        '        margin-bottom: λ10λpx;\n'
        '        /* column-gap: λ10λpx; */\n'
        '    }\n'
        '\n'
        '        .new-game-promotion {\n'
        '            z-index: inherit;\n'
        '            display: grid;\n'
        '            grid-row: 1;\n'
        '            grid-column: 3;\n'
        '            grid-template-columns: λ120λpx λ147λpx; \n'
        '            grid-template-rows: λ30λpx; \n'
        '            text-align: left;\n'
        '        }\n'
        '\n'
        '            .new-game-promotion-label {\n'
        '                z-index: inherit;\n'
        '                grid-column: 1;\n'
        '                grid-row: 1;\n'
        '                text-align: left;\n'
        "                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, "
        'sans-serif;\n'
        '                font-size: λ20λpx;\n'
        '                padding-left: λ8λpx;\n'
        '                padding-top: λ3λpx;\n'
        '                color: #a9a9a9;\n'
        '            }\n'
        '\n'
        '            .new-game-promotion-checkbox-container {\n'
        '                z-index: inherit;\n'
        '                grid-column: 2;\n'
        '            }\n'
        '\n'
        '\n'
        '        .new-game-substitute {\n'
        '            z-index: inherit;\n'
        '            display: grid;\n'
        '            grid-template-columns: λ60λpx λ272λpx; \n'
        '            grid-row: 1;\n'
        '            grid-column: 4;\n'
        '        }\n'
        '\n'
        '            .new-game-sub-label {\n'
        '                z-index: inherit;\n'
        '                grid-column: 1;\n'
        '                grid-row: 1;\n'
        '                color: #a9a9a9;\n'
        '                text-align: left;\n'
        "                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, "
        'sans-serif;\n'
        '                font-size: λ20λpx;\n'
        '                padding-top: λ2λpx;\n'
        '            }\n'
        '\n'
        '            .new-game-sub-dropdown-container {\n'
        '                z-index: inherit;\n'
        '                grid-column: 2;\n'
        '                grid-row: 1;\n'
        '                margin-left: λ6λpx;\n'
        '            }\n',
        '.new-game-sub-dropdown {\n'
        '    position: relative;\n'
        '    top: λ8λpx;\n'
        '    width: λ140λpx;\n'
        '    height: λ18λpx;\n'
        '    color: #a9a9a9;\n'
        '    background-color: #515151;\n'
        '    cursor: pointer;\n'
        '}',
        '\n'
        '.new-game-customize-window {\n'
        '    position: relative;\n'
        '    z-index: 1;\n'
        '    left: λ250λpx; \n'
        '    top: λ120λpx;\n'
        '    background-color: #515151;\n'
        '    height: λ1100λpx; \n'
        '    width: λ1020λpx; \n'
        '    border: λ1λpx solid #969696;\n'
        '}\n'
        '\n'
        '.new-game-customize-top-bar {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    top: λ0λpx;\n'
        '    left: λ0λpx;\n'
        '    height: λ48λpx;\n'
        '    width: λ1020λpx;\n'
        '    /* border: λ1λpx dashed magenta; */\n'
        '    border-bottom: λ1λpx solid #707070;\n'
        '}\n'
        '\n'
        '.new-game-customize-top-bar-title {\n'
        '    position: absolute;\n'
        '    left: λ10.5λpx;\n'
        '    top: -λ4λpx;\n'
        '    color: #b6b6b6;\n'
        '    font-size: λ40λpx;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    text-align: center;\n'
        '    padding-top: -λ4λpx;\n'
        '\n'
        '}\n'
        '\n'
        '.new-game-piece-profiles {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    display: grid;\n'
        '    top: λ50.7λpx;\n'
        '    grid-template-columns: 1fr;\n'
        '    background-color: #515151;\n'
        '    height: λ800λpx;\n'
        '    width: λ1020λpx;\n'
        '    overflow: scroll;\n'
        '    border-bottom: λ1λpx solid #707070;\n'
        '}\n'
        '\n'
        '.new-game-display-on {\n'
        '    display: initial;\n'
        '}\n'
        '\n'
        '.new-game-display-off {\n'
        '    display: none;\n'
        '}\n'
        '\n'
        '.new-game-bottom-bar {\n'
        '    position: absolute;\n'
        '    display: grid;\n'
        '    left: λ0λpx;\n'
        '    top: λ850λpx;\n'
        '    grid-template-columns: λ85λpx λ455λpx λ480λpx;\n'
        '    grid-template-rows: λ38λpx λ38λpx λ38λpx λ38λpx λ38λpx;\n'
        '    /* row-gap: λ5λpx; */\n'
        '}\n'
        '\n'
        '.new-game-promo-label {\n'
        '    grid-column: 3;\n'
        '    grid-row: 1 / 2;\n'
        '    color: #a9a9a9;\n'
        '     text-align: center;\n'
        "     font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '     font-size: λ25λpx;\n'
        '     border: λ1λpx solid #707070;\n'
        '}\n'
        '\n'
        '.new-game-promo-list-container {\n'
        '    grid-column: 3;\n'
        '    grid-row: 2 / 6;\n'
        '    color: #a9a9a9;\n'
        '    text-align: center;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    font-size: λ20λpx;\n'
        '    overflow: hidden;\n'
        '    text-overflow: ellipsis;\n'
        '    border: λ1λpx solid #707070;\n'
        '}\n',
        '.ilb-ei {\n'
        '   display: inline-block;\n'
        '   width: λ14λpx;\n'
        '   height: λ14λpx;\n'
        '}\n'
        '\n'
        '.ilb-ei-img {\n'
        '    width: λ14λpx;\n'
        '    height: λ14λpx;\n'
        '}',
        '.new-game-player-type-label {\n'
        '    position: absolute;\n'
        '    top: λ12λpx;\n'
        '    left: λ280λpx;\n'
        '    color: #a9a9a9;\n'
        '    font-size: λ20λpx;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    text-align: center;\n'
        '}\n'
        '\n'
        '.new-game-player-type-dropdown {\n'
        '    position: absolute;\n'
        '    top: λ14λpx;\n'
        '    left: λ350λpx;\n'
        '    width: λ200λpx;\n'
        '    height: λ22λpx;\n'
        '    background-color: #515151;\n'
        '    border: λ1λpx solid #707070;\n'
        '    color: #a9a9a9;\n'
        '    font-size: λ16λpx;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    cursor: pointer;\n'
        '}',
        '.new-game-promo-all {\n'
        '    position: absolute;\n'
        '    z-index: 3;\n'
        '    display: grid;\n'
        '    left: λ572λpx;\n'
        '    top: λ6λpx;\n'
        '    grid-template-columns: λ98λpx λ25λpx; \n'
        '    grid-template-rows: λ36λpx; \n'
        '    text-align: left;\n'
        '}\n'
        '\n'
        '.new-game-promo-all-label {\n'
        '    grid-column: 1;\n'
        '    font-size: λ20λpx;\n'
        '    padding-top: λ5λpx;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    color: #a9a9a9;\n'
        '    /* border: λ1λpx dashed white; */\n'
        '}\n'
        '\n'
        '.new-game-promo-all-checkbox-container {\n'
        '    grid-column: 2;\n'
        '    /* border: λ1λpx dashed white;  */\n'
        '}\n'
        '\n'
        '.new-game-promo-all-checkbox {\n'
        '    position: relative;\n'
        '    top: λ9λpx;\n'
        '    width: λ18λpx; \n'
        '    height: λ18λpx; \n'
        '    background-color: #515151;\n'
        '    border: λ2λpx solid #707070;\n'
        '    border-radius: λ5λpx;\n'
        '    cursor: pointer;\n'
        '} \n'
        '\n'
        '\n'
        '.new-game-promo-all-checkbox-selected {\n'
        '    position: relative;\n'
        '    top: λ9λpx;\n'
        '    width: λ18λpx; \n'
        '    height: λ18λpx; \n'
        '    background-color: #515151;\n'
        '    border: λ2λpx solid #969696;\n'
        '    border-radius: λ5λpx;\n'
        '    cursor: pointer;\n'
        '} \n'
        '\n'
        '.new-game-checked {\n'
        '    position: absolute;\n'
        '    max-height: λ18λpx; \n'
        '    max-width: λ18λpx; \n'
        '    padding: λ1λpx;\n'
        '    object-fit: contain;\n'
        '}\n',
        '.new-game-customize-top-bar-search {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    width: λ280λpx;\n'
        '    height: λ26λpx;\n'
        '    left: λ720λpx;\n'
        '    top: λ10λpx;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    background-color: #515151;\n'
        '    border: λ2λpx solid #707070;\n'
        '    border-radius: λ9λpx;\n'
        '}\n'
        '.new-game-customize-top-bar-search-magnifying-glass {\n'
        '    position: absolute;\n'
        '    left: λ4λpx; \n'
        '    width:λ16λpx; \n'
        '    height:λ16λpx;\n'
        '    margin-top: λ6λpx;\n'
        '}\n'
        '.new-game-customize-top-bar-search-box {\n'
        '    position: absolute;\n'
        '    left: λ21λpx;\n'
        '    top: λ0λpx;\n'
        '    height: λ24λpx;\n'
        '    width: λ253λpx;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    color: #c4c4c4;\n'
        '    /* color: #5c9fd2; */\n'
        '    background-color: #515151;\n'
        '    border: none;\n'
        '    border-radius: λ9λpx;\n'
        '    outline: none;\n'
        '}\n'
        '\n']
    ))
