import re
from pprint import pprint


def tag_matches(source_strs):
    """Step 3. enclose every matching value with λ's """
    for i in range(len(source_strs)):
        source_strs[i] = re.sub("(\d+\.*\d*)(?=px|pc|pt|in|mm|cm|%|vw|vh|vmin|bmax|rem|ch|ex|em)", r'λ\1λ', source_strs[i])
    return source_strs


if __name__ == "__main__":
    pprint(tag_matches([
        '.new-game-accept-customization {\n'
        '    position: absolute;\n'
        '    z-index: 2;\n'
        '    width: 90px; \n'
        '    height: 40px; \n'
        '    left: 1180px; \n'
        '    top: 1180px; \n'
        '    font-size: 18px;\n'
        '    color: #b6b6b6;\n'
        '    background-color: #6c6c6c;\n'
        '    border: 1px solid #7e7e7e;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    border-radius: 6px;\n'
        '    cursor: pointer;\n'
        '}\n'
        '.new-game-accept-customization:hover {\n'
        '    color: #606060;\n'
        '    background-color: #b6b6b6;\n'
        '} ',
        '.new-game-promo-list {\n'
        '    display: grid;\n'
        '    grid-template-columns: 480px;\n'
        '    grid-template-rows: 15px 24px 24px 24px 24px 24px 15px;\n'
        '    border: 1px solid #707070\n'
        '\n'
        '}\n'
        '\n'
        '.promo-list-item {\n'
        '    color: #a9a9a9;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    font-size: 15px;\n'
        '    text-align: left;\n'
        '    padding-top: 4px;\n'
        '    overflow: hidden;\n'
        '    text-overflow: ellipsis;\n'
        '}\n'
        '\n'
        '.p-list-item1 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 2;\n'
        '    background-color: #5D5D5D;\n'
        '}\n'
        '\n'
        '.p-list-item2 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 3;\n'
        '    background-color: #515151;\n'
        '}\n'
        '\n'
        '.p-list-item3 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 4;\n'
        '    background-color: #5D5D5D;\n'
        '}\n'
        '\n'
        '.p-list-item4 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 5;\n'
        '    background-color: #515151;\n'
        '}\n'
        '\n'
        '.p-list-item5 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 6;\n'
        '    background-color: #5D5D5D;\n'
        '} ',
        '\n'
        '.promo-list-up-arrow {\n'
        '    grid-column: 1;\n'
        '    grid-row: 1;\n'
        '    cursor: pointer;\n'
        '}\n'
        '\n'
        '.promo-list-down-arrow {\n'
        '    grid-column: 1;\n'
        '    grid-row: 7;\n'
        '    cursor: pointer;\n'
        '}\n'
        '\n'
        '.promo-list-scroll-arrow {\n'
        '    position: absolute;\n'
        '    margin-top: 3px;\n'
        '    width: 7px;\n'
        '    height: 6px;\n'
        '}',
        '.new-game-subs-header {\n'
        '    grid-column: 1 / 3;\n'
        '    grid-row: 1;\n'
        '    text-align: center;\n'
        '    color: #a9a9a9;\n'
        '    font-size: 25px;\n'
        '    padding-left: 85px;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    border: 1px solid #707070;\n'
        '}\n'
        '\n'
        ' .new-game-bishop-label {\n'
        '    grid-column: 1;\n'
        '    grid-row: 3;\n'
        '    text-align: left;\n'
        '    font-size: 20px;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    color: #a9a9a9;\n'
        '    padding-left: 10px;\n'
        '    padding-top: 5px;\n'
        '    background-color: #4e4e4e;\n'
        '    border-right: 1px solid #707070;\n'
        '    /* border: 1px solid #707070; */\n'
        '}\n'
        '.new-game-bishop-value {\n'
        '    grid-column: 2;\n'
        '    color: #a9a9a9;\n'
        '    background-color: #515151;\n'
        '    text-align: center;\n'
        '    font-size: 20px;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    grid-row: 3;\n'
        '    padding-left: 10px;\n'
        '    /* border: 1px solid #707070; */\n'
        '}\n'
        '\n'
        '.new-game-knight-label {\n'
        '    grid-column: 1;\n'
        '    grid-row: 4;\n'
        '    text-align: left;\n'
        '    font-size: 20px;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    color: #a9a9a9;\n'
        '    background-color: #4e4e4e;\n'
        '    border-right: 1px solid #707070;\n'
        '    padding-left: 10px;\n'
        '    padding-top: 5px;\n'
        '    /* border: 1px solid #707070; */\n'
        '}\n'
        '.new-game-knight-value {\n'
        '    grid-column: 2;\n'
        '    color: #a9a9a9;\n'
        '    background-color: #5D5D5D;\n'
        '    text-align: center;\n'
        '    font-size: 20px;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    grid-row: 4;\n'
        '    padding-left: 10px;\n'
        '    /* border: 1px solid #707070; */\n'
        '}\n'
        '\n'
        '.new-game-rook-label {\n'
        '    grid-column: 1;\n'
        '    grid-row: 2;\n'
        '    text-align: left;\n'
        '    font-size: 20px;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    color: #a9a9a9;\n'
        '    background-color: #4e4e4e;\n'
        '    border-right: 1px solid #707070;\n'
        '    padding-left: 10px;\n'
        '    padding-top: 5px;\n'
        '    /* border: 1px solid #707070; */\n'
        '}\n'
        '.new-game-rook-value {\n'
        '    grid-column: 2;\n'
        '    color: #a9a9a9;\n'
        '    background-color: #5D5D5D;\n'
        '    text-align: center;\n'
        '    font-size: 20px;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    grid-row: 2;\n'
        '    padding-left: 10px;\n'
        '    /* border: 1px solid #707070; */\n'
        '\n'
        '}\n'
        '\n'
        '.new-game-queen-label {\n'
        '    grid-column: 1;\n'
        '    grid-row: 5;\n'
        '    text-align: left;\n'
        '    font-size: 20px;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    color: #a9a9a9;\n'
        '    background-color: #4e4e4e;\n'
        '    border-right: 1px solid #707070;\n'
        '    padding-left: 10px;\n'
        '    padding-top: 5px;\n'
        '    border-bottom: 1px solid #707070;\n'
        '}\n'
        '.new-game-queen-value {\n'
        '    grid-column: 2;\n'
        '    color: #a9a9a9;\n'
        '    background-color: #515151;\n'
        '    text-align: center;\n'
        '    font-size: 20px;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    padding-left: 10px;\n'
        '    grid-row: 5;\n'
        '    border-bottom: 1px solid #707070;\n'
        '}\n'
        '\n',
        '\n'
        '\n'
        '.new-game-display-board {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    grid-column: 1 \\ 3;\n'
        '    grid-row: 2;\n'
        '}',
        '.new-game-display-piece {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    width: 20px;\n'
        '    height: 20px;\n'
        '}',
        '.new-game-display-board-sqr1 {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    width: 40px;\n'
        '    height: 40px;\n'
        '    background-color: #707070;\n'
        '}\n'
        '\n'
        '.new-game-display-board-sqr2 {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    width: 40px;\n'
        '    height: 40px;\n'
        '    background-color: white;\n'
        '}\n'
        '\n'
        '.new-game-display-board-span-sqr {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    width: 40px;\n'
        '    height: 40px;\n'
        '    background-color: #EC2525;\n'
        '}\n'
        '\n'
        '.new-game-display-board-offset-sqr {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    width: 40px;\n'
        '    height: 40px;\n'
        '    background-color: #8b0000;\n'
        '}',
        '.new-game-expand-modal {\n'
        '    position: fixed;\n'
        '    z-index: 1;\n'
        '    top: 0;\n'
        '    left: 0;\n'
        '    width:100%;\n'
        '    height: 100%;\n'
        '    background: rgba(0, 0, 0, 0.5);\n'
        '  }\n'
        '\n'
        '  .new-game-expand-modal-window {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    display: grid;\n'
        '    left: 300px; \n'
        '    top: 300px; \n'
        '    width: 299px;\n'
        '    grid-template-columns: 300px 20px; \n'
        '    grid-template-rows: 20px 320px;\n'
        '    background-color: #515151;\n'
        '    color: white;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    font-size: 12px; \n'
        '    overflow: wrap;\n'
        '}\n'
        '\n'
        '.new-game-expand-modal-window-title {\n'
        '  z-index: inherit;\n'
        '  grid-row: 1;\n'
        '  grid-column: 1;\n'
        '  color: white;\n'
        '  background-color: #515151;\n'
        '  border: 1px solid #707070;\n'
        "  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '  font-size: 15px;\n'
        '  overflow: hidden;\n'
        '  text-overflow: ellipsis;\n'
        '}\n'
        '\n'
        '.new-game-tooltip {\n'
        '  display: block;\n'
        '  position: absolute;\n'
        '  z-index: 3;\n'
        '  width: 400px;\n'
        '  left: 600px;\n'
        '  top: 300px;\n'
        '  padding: 5px 0;\n'
        '  color: #fff;\n'
        '  background-color: #515151;\n'
        '  font-size: 15px;\n'
        "  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '  border-radius: 6px;\n'
        '  word-wrap: break-word;\n'
        '}\n'
        '\n'
        '  /* .title:hover .tooltip {\n'
        '    visibility: visible;\n'
        '    z-index: 10;\n'
        '  } */\n'
        '\n'
        '.new-game-modal-window-unexpand {\n'
        '  z-index: inherit;\n'
        '  grid-row: 1;\n'
        '  grid-column: 2;\n'
        '  max-height: 18px; \n'
        '  max-width: 18px;\n'
        '  background-color: #515151;\n'
        '  border: 1px solid #707070;\n'
        '  cursor: pointer;\n'
        '} \n'
        '\n'
        '\n',
        '.new-game-spans-header {\n'
        '    grid-row: 1;\n'
        '    grid-column: 2;\n'
        '    display: grid;\n'
        '    grid-template-rows: 30px;\n'
        '    grid-template-columns: 370px 30px;\n'
        '    column-gap: 20px;\n'
        '    border: 1px solid #707070;\n'
        '}\n'
        '\n'
        '.new-game-offsets-header {\n'
        '    grid-row: 1;\n'
        '    grid-column: 3;\n'
        '    display: grid;\n'
        '    grid-template-rows: 30px;\n'
        '    grid-template-columns: 370px 30px;\n'
        '    column-gap: 20px;\n'
        '    border: 1px solid #707070;\n'
        '}\n'
        '\n'
        '    .new-game-piece-wb-piece-name {\n'
        '        grid-row: 1;\n'
        '        grid-column: 1;\n'
        "        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '        font-size: 15px;\n'
        '        padding-top: 6px;\n'
        '        padding-left: 50px;\n'
        '        color: #a9a9a9;\n'
        '        text-align: center;\n'
        '        overflow: hidden;\n'
        '        text-overflow: ellipsis;\n'
        '    }\n'
        '\n'
        '    .new-game-piece-expand-modal {\n'
        '        grid-row: 1;\n'
        '        grid-column: 2;\n'
        '        cursor: pointer;\n'
        '    }',
        '.new-game-spans-table {\n'
        '    grid-column: 2;\n'
        '    grid-row: 2;\n'
        '    display: grid;\n'
        '    grid-template-columns: 420px;\n'
        '    grid-template-rows: 15px 24px 24px 24px 24px 24px 15px;\n'
        '    border: 1px solid #707070\n'
        '}\n'
        '\n'
        '.new-game-offsets-table {\n'
        '    grid-column: 3;\n'
        '    grid-row: 2;\n'
        '    display: grid;\n'
        '    grid-template-columns: 420px;\n'
        '    grid-template-rows: 15px 24px 24px 24px 24px 24px 15px;\n'
        '    border: 1px solid #707070;\n'
        '}\n'
        '\n'
        '.range-list-item {\n'
        '    color: #a9a9a9;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    font-size: 12px;\n'
        '    text-align: left;\n'
        '}\n'
        '\n'
        '.list-item1 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 2;\n'
        '    background-color: #5D5D5D;\n'
        '}\n'
        '\n'
        '.list-item2 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 3;\n'
        '    background-color: #515151;\n'
        '}\n'
        '\n'
        '.list-item3 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 4;\n'
        '    background-color: #5D5D5D;\n'
        '}\n'
        '\n'
        '.list-item4 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 5;\n'
        '    background-color: #515151;\n'
        '}\n'
        '\n'
        '.list-item5 {\n'
        '    grid-column: 1;\n'
        '    grid-row: 6;\n'
        '    background-color: #5D5D5D;\n'
        '}',
        '\n'
        '.new-game-spans-up-arrow {\n'
        '    grid-column: 1;\n'
        '    grid-row: 1;\n'
        '    cursor: pointer;\n'
        '}\n'
        '\n'
        '.new-game-spans-down-arrow {\n'
        '    grid-column: 1;\n'
        '    grid-row: 7;\n'
        '    cursor: pointer;\n'
        '}\n'
        '\n'
        ' .new-game-offsets-up-arrow {\n'
        '    grid-column: 1;\n'
        '    grid-row: 1;\n'
        '    cursor: pointer;\n'
        '}\n'
        '\n'
        ' .new-game-offsets-down-arrow {\n'
        '    grid-column: 1;\n'
        '    grid-row: 7;\n'
        '    cursor: pointer;\n'
        '}\n'
        '\n'
        '.scroll-arrow {\n'
        '    position: relative;\n'
        '    top: -4px;\n'
        '    left: 207px;\n'
        '    width: 6px;\n'
        '    height: 5px;\n'
        '}',
        '\n'
        '\n'
        '.new-game-w-or-b-profile {\n'
        '    z-index: inherit;\n'
        '    display: grid;\n'
        '    height: 180px;\n'
        '    grid-template-columns: 150px 420px 420px;\n'
        '    grid-template-rows: 30px 150px;\n'
        '    margin-top: 20px;\n'
        '    background-color: #515151;\n'
        '    overflow: hidden;\n'
        '    text-overflow: ellipsis;\n'
        '}\n'
        '    \n'
        '    .new-game-w-or-b-profile-img-label {\n'
        '        grid-column:1;\n'
        '        grid-row: 1;\n'
        '        font-size: 15px;\n'
        "        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '        text-align: center;\n'
        '        padding-top: 6px;\n'
        '        color: #a9a9a9;\n'
        '        border: 1px solid #707070;\n'
        '    }\n'
        '\n'
        '    .new-game-w-or-b-profile-img-window {\n'
        '        z-index: inherit;\n'
        '        grid-column: 1;\n'
        '        grid-row: 2;\n'
        '        object-fit: cover;\n'
        '        border: 1px solid #707070;\n'
        '    }\n'
        '\n'
        '        .new-game-w-or-b-profile-img-window img {\n'
        '            z-index: inherit;\n'
        '            width: 150px; \n'
        '            height: 150px;\n'
        '            border-radius: 5px;\n'
        '        }\n'
        '\n'
        '    .new-game-w-or-b-profile-spans-label {\n'
        '        grid-column: 2;\n'
        '        grid-row: 1;\n'
        '        \n'
        '    }\n'
        '\n'
        '    .new-game-w-or-b-profile-offsets-label {\n'
        '        grid-column: 3;\n'
        '        grid-row: 1;\n'
        '        \n'
        '    }\n',
        '.new-game-promotion-checkbox {\n'
        '    width: 18px; \n'
        '    height: 18px; \n'
        '    margin-top: 5px; \n'
        '    background-color: #515151;\n'
        '    border: 2px solid #707070;\n'
        '    border-radius: 5px;\n'
        '    cursor: pointer;\n'
        '} .new-game-promotion-checkbox-selected {\n'
        '    width: 18px; \n'
        '    height: 18px; \n'
        '    margin-top: 5px; \n'
        '    background-color: #515151;\n'
        '    border: 2px solid #969696;\n'
        '    border-radius: 5px;\n'
        '    cursor: pointer;\n'
        '}\n'
        '.new-game-promotion-checkbox-checkmark {\n'
        '    position: absolute;\n'
        '    max-height: 18px; \n'
        '    max-width: 18px; \n'
        '    padding: 1px;\n'
        '    object-fit: contain;\n'
        '}\n',
        '.new-game-name-tooltip {\n'
        '    position: absolute;\n'
        '    display: block;\n'
        '    left: 50%;\n'
        '    top: 50%;\n'
        '    z-index: 3;\n'
        '    word-wrap: break-word;\n'
        '    color: white;\n'
        '\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    border-radius: 5px;\n'
        '}',
        '.new-game-name-of-piece {\n'
        '    z-index: inherit;\n'
        '    grid-row: 1;\n'
        '    grid-column: 1 / 3;\n'
        '    padding-top: 3px;\n'
        '    padding-left: 9px; \n'
        '    padding-bottom: 3px; \n'
        '    border-radius: 3px; \n'
        '    color: #a9a9a9;\n'
        '    font-size: 21px; \n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    overflow: hidden;\n'
        '    text-overflow: ellipsis;\n'
        '}\n',
        '\n'
        '.new-game-profile {\n'
        '    z-index: inherit;\n'
        '    height: 480px;\n'
        '    border-bottom: 1px solid #707070;\n'
        '}\n'
        '\n'
        '    /*container for w-or-b-profile*/\n'
        '    .new-game-profile-item {\n'
        '        z-index: inherit;\n'
        '        height: 180px;\n'
        '        background-color: #515151;\n'
        '        margin-bottom: 20px;\n'
        '    }\n'
        '\n'
        '    .new-game-profile-header {\n'
        '        display: grid;\n'
        '        z-index: inherit;\n'
        '        width: 900px;\n'
        '        grid-template-rows: 30px;\n'
        '        grid-template-columns: 200px 100px 268px 260px;\n'
        '        margin-bottom: 10px;\n'
        '        /* column-gap: 10px; */\n'
        '    }\n'
        '\n'
        '        .new-game-promotion {\n'
        '            z-index: inherit;\n'
        '            display: grid;\n'
        '            grid-row: 1;\n'
        '            grid-column: 3;\n'
        '            grid-template-columns: 120px 147px; \n'
        '            grid-template-rows: 30px; \n'
        '            text-align: left;\n'
        '        }\n'
        '\n'
        '            .new-game-promotion-label {\n'
        '                z-index: inherit;\n'
        '                grid-column: 1;\n'
        '                grid-row: 1;\n'
        '                text-align: left;\n'
        "                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, "
        'sans-serif;\n'
        '                font-size: 20px;\n'
        '                padding-left: 8px;\n'
        '                padding-top: 3px;\n'
        '                color: #a9a9a9;\n'
        '            }\n'
        '\n'
        '            .new-game-promotion-checkbox-container {\n'
        '                z-index: inherit;\n'
        '                grid-column: 2;\n'
        '            }\n'
        '\n'
        '\n'
        '        .new-game-substitute {\n'
        '            z-index: inherit;\n'
        '            display: grid;\n'
        '            grid-template-columns: 60px 272px; \n'
        '            grid-row: 1;\n'
        '            grid-column: 4;\n'
        '        }\n'
        '\n'
        '            .new-game-sub-label {\n'
        '                z-index: inherit;\n'
        '                grid-column: 1;\n'
        '                grid-row: 1;\n'
        '                color: #a9a9a9;\n'
        '                text-align: left;\n'
        "                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, "
        'sans-serif;\n'
        '                font-size: 20px;\n'
        '                padding-top: 2px;\n'
        '            }\n'
        '\n'
        '            .new-game-sub-dropdown-container {\n'
        '                z-index: inherit;\n'
        '                grid-column: 2;\n'
        '                grid-row: 1;\n'
        '                margin-left: 6px;\n'
        '            }\n',
        '.new-game-sub-dropdown {\n'
        '    position: relative;\n'
        '    top: 8px;\n'
        '    width: 140px;\n'
        '    height: 18px;\n'
        '    color: #a9a9a9;\n'
        '    background-color: #515151;\n'
        '    cursor: pointer;\n'
        '}',
        '\n'
        '.new-game-customize-window {\n'
        '    position: relative;\n'
        '    z-index: 1;\n'
        '    left: 250px; \n'
        '    top: 120px;\n'
        '    background-color: #515151;\n'
        '    height: 1100px; \n'
        '    width: 1020px; \n'
        '    border: 1px solid #969696;\n'
        '}\n'
        '\n'
        '.new-game-customize-top-bar {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    top: 0px;\n'
        '    left: 0px;\n'
        '    height: 48px;\n'
        '    width: 1020px;\n'
        '    /* border: 1px dashed magenta; */\n'
        '    border-bottom: 1px solid #707070;\n'
        '}\n'
        '\n'
        '.new-game-customize-top-bar-title {\n'
        '    position: absolute;\n'
        '    left: 10.5px;\n'
        '    top: -4px;\n'
        '    color: #b6b6b6;\n'
        '    font-size: 40px;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    text-align: center;\n'
        '    padding-top: -4px;\n'
        '\n'
        '}\n'
        '\n'
        '.new-game-piece-profiles {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    display: grid;\n'
        '    top: 50.7px;\n'
        '    grid-template-columns: 1fr;\n'
        '    background-color: #515151;\n'
        '    height: 800px;\n'
        '    width: 1020px;\n'
        '    overflow: scroll;\n'
        '    border-bottom: 1px solid #707070;\n'
        '}\n'
        '\n'
        '.new-game-display-on {\n'
        '    display: initial;\n'
        '}\n'
        '\n'
        '.new-game-display-off {\n'
        '    display: none;\n'
        '}\n'
        '\n'
        '.new-game-bottom-bar {\n'
        '    position: absolute;\n'
        '    display: grid;\n'
        '    left: 0px;\n'
        '    top: 850px;\n'
        '    grid-template-columns: 85px 455px 480px;\n'
        '    grid-template-rows: 38px 38px 38px 38px 38px;\n'
        '    /* row-gap: 5px; */\n'
        '}\n'
        '\n'
        '.new-game-promo-label {\n'
        '    grid-column: 3;\n'
        '    grid-row: 1 / 2;\n'
        '    color: #a9a9a9;\n'
        '     text-align: center;\n'
        "     font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '     font-size: 25px;\n'
        '     border: 1px solid #707070;\n'
        '}\n'
        '\n'
        '.new-game-promo-list-container {\n'
        '    grid-column: 3;\n'
        '    grid-row: 2 / 6;\n'
        '    color: #a9a9a9;\n'
        '    text-align: center;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    font-size: 20px;\n'
        '    overflow: hidden;\n'
        '    text-overflow: ellipsis;\n'
        '    border: 1px solid #707070;\n'
        '}\n',
        '.ilb-ei {\n'
        '   display: inline-block;\n'
        '   width: 14px;\n'
        '   height: 14px;\n'
        '}\n'
        '\n'
        '.ilb-ei-img {\n'
        '    width: 14px;\n'
        '    height: 14px;\n'
        '}',
        '.new-game-player-type-label {\n'
        '    position: absolute;\n'
        '    top: 12px;\n'
        '    left: 280px;\n'
        '    color: #a9a9a9;\n'
        '    font-size: 20px;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    text-align: center;\n'
        '}\n'
        '\n'
        '.new-game-player-type-dropdown {\n'
        '    position: absolute;\n'
        '    top: 14px;\n'
        '    left: 350px;\n'
        '    width: 200px;\n'
        '    height: 22px;\n'
        '    background-color: #515151;\n'
        '    border: 1px solid #707070;\n'
        '    color: #a9a9a9;\n'
        '    font-size: 16px;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    cursor: pointer;\n'
        '}',
        '.new-game-promo-all {\n'
        '    position: absolute;\n'
        '    z-index: 3;\n'
        '    display: grid;\n'
        '    left: 572px;\n'
        '    top: 6px;\n'
        '    grid-template-columns: 98px 25px; \n'
        '    grid-template-rows: 36px; \n'
        '    text-align: left;\n'
        '}\n'
        '\n'
        '.new-game-promo-all-label {\n'
        '    grid-column: 1;\n'
        '    font-size: 20px;\n'
        '    padding-top: 5px;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    color: #a9a9a9;\n'
        '    /* border: 1px dashed white; */\n'
        '}\n'
        '\n'
        '.new-game-promo-all-checkbox-container {\n'
        '    grid-column: 2;\n'
        '    /* border: 1px dashed white;  */\n'
        '}\n'
        '\n'
        '.new-game-promo-all-checkbox {\n'
        '    position: relative;\n'
        '    top: 9px;\n'
        '    width: 18px; \n'
        '    height: 18px; \n'
        '    background-color: #515151;\n'
        '    border: 2px solid #707070;\n'
        '    border-radius: 5px;\n'
        '    cursor: pointer;\n'
        '} \n'
        '\n'
        '\n'
        '.new-game-promo-all-checkbox-selected {\n'
        '    position: relative;\n'
        '    top: 9px;\n'
        '    width: 18px; \n'
        '    height: 18px; \n'
        '    background-color: #515151;\n'
        '    border: 2px solid #969696;\n'
        '    border-radius: 5px;\n'
        '    cursor: pointer;\n'
        '} \n'
        '\n'
        '.new-game-checked {\n'
        '    position: absolute;\n'
        '    max-height: 18px; \n'
        '    max-width: 18px; \n'
        '    padding: 1px;\n'
        '    object-fit: contain;\n'
        '}\n',
        '.new-game-customize-top-bar-search {\n'
        '    position: absolute;\n'
        '    z-index: inherit;\n'
        '    width: 280px;\n'
        '    height: 26px;\n'
        '    left: 720px;\n'
        '    top: 10px;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    background-color: #515151;\n'
        '    border: 2px solid #707070;\n'
        '    border-radius: 9px;\n'
        '}\n'
        '.new-game-customize-top-bar-search-magnifying-glass {\n'
        '    position: absolute;\n'
        '    left: 4px; \n'
        '    width:16px; \n'
        '    height:16px;\n'
        '    margin-top: 6px;\n'
        '}\n'
        '.new-game-customize-top-bar-search-box {\n'
        '    position: absolute;\n'
        '    left: 21px;\n'
        '    top: 0px;\n'
        '    height: 24px;\n'
        '    width: 253px;\n'
        "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        '    color: #c4c4c4;\n'
        '    /* color: #5c9fd2; */\n'
        '    background-color: #515151;\n'
        '    border: none;\n'
        '    border-radius: 9px;\n'
        '    outline: none;\n'
        '}\n'
        '\n'
    ]))
